#!/usr/bin/env bash

# Test fixture for 'Check shell command' workflow tests.
#
# Latest revision: 2026-04-01
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

echo "Hello, world!" | tee hello.txt
