# Reusable workflow for checking shell commands;
# fails on non-zero command exit code.
#
# Latest revision: 2026-03-26
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Check command

on:
  workflow_call:
    inputs:
      command:
        description: "Command to check"
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: ${{ inputs.command }}
