# GitHub Actions test for 'Check script' reusable workflow;
# runs a trivial script to verify success detection.
#
# Latest revision: 2026-03-27
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Test 'Check script' workflow

on:
  push:
  workflow_dispatch:

jobs:
  test-success:
    uses: mystikolaos/actions/.github/workflows/check-script.yml@main
    with:
      script: "test/hello"
